edition = "2024"

format_code_in_doc_comments = true
normalize_comments = true
wrap_comments = false

doc_comment_code_block_width = 100
comment_width = 100

group_imports = "StdExternalCrate"
imports_granularity = "Crate"
imports_layout = "HorizontalVertical"
