[target.xtensa-esp32s3-none-elf]
runner = [
  "espflash",
  "flash",
  "--monitor",
  "--chip",
  "esp32s3",
  "--log-format",
  "defmt", 
  "--output-format",
  "[{L:severity:4}] {s}"
]

[env]
DEFMT_LOG="info"
ESP_HAL_CONFIG_PSRAM_MODE = "octal"

[build]
rustflags = [
  "-C", "link-arg=-nostartfiles",
]

target = "xtensa-esp32s3-none-elf"

[unstable]
build-std = ["alloc", "core"]
